In [1]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Display Settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

# Ignore Warnings
import warnings
warnings.filterwarnings("ignore")

# Plot Style
plt.style.use("ggplot")

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [2]:
df = pd.read_csv("../data/raw/medical_insurance.csv")

In [3]:
df.head()

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,policy_changes_last_2yrs,provider_quality,risk_score,annual_medical_cost,annual_premium,monthly_premium,claims_count,avg_claim_amount,total_claims_paid,chronic_count,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,1,27.4,Never,NaN,2,0,0,4,121.0,76.0,123.8,5.28,PPO,Bronze,1000,20,4,0,3.73,0.5714,6938.06,876.05,73.00,1,4672.59,4672.59,1,0,0,0,0,0,0,0,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,1,26.6,Never,Weekly,2,0,0,3,131.0,79.0,97.3,4.82,POS,Gold,1000,10,1,0,3.10,1.0000,1632.61,445.10,37.09,4,297.27,1189.08,2,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,3,31.5,Never,NaN,1,0,0,4,160.0,84.0,129.5,5.51,HMO,Platinum,500,20,10,0,3.90,1.0000,7661.01,1538.02,128.17,0,0.00,0.00,3,1,0,0,0,0,1,0,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,3,31.6,Never,NaN,0,0,0,1,104.0,68.0,160.3,8.50,HMO,Silver,500,20,5,0,3.89,0.2857,5130.27,820.63,68.39,0,0.00,0.00,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,0,30.5,Never,Daily,3,0,0,2,136.0,83.0,171.0,5.20,POS,Platinum,500,10,7,0,3.90,0.8681,1700.73,500.93,41.74,1,1002.24,1002.24,2,1,0,0,0,0,0,0,0,1,0,2,0,1,1,0,1,0

In [6]:
df.shape

(100000, 54)

In [7]:
df.columns

Index(['person_id', 'age', 'sex', 'region', 'urban_rural', 'income',
       'education', 'marital_status', 'employment_status', 'household_size',
       'dependents', 'bmi', 'smoker', 'alcohol_freq', 'visits_last_year',
       'hospitalizations_last_3yrs', 'days_hospitalized_last_3yrs',
       'medication_count', 'systolic_bp', 'diastolic_bp', 'ldl', 'hba1c',
       'plan_type', 'network_tier', 'deductible', 'copay', 'policy_term_years',
       'policy_changes_last_2yrs', 'provider_quality', 'risk_score',
       'annual_medical_cost', 'annual_premium', 'monthly_premium',
       'claims_count', 'avg_claim_amount', 'total_claims_paid',
       'chronic_count', 'hypertension', 'diabetes', 'asthma', 'copd',
       'cardiovascular_disease', 'cancer_history', 'kidney_disease',
       'liver_disease', 'arthritis', 'mental_health', 'proc_imaging_count',
       'proc_surgery_count', 'proc_physio_count', 'proc_consult_count',
       'proc_lab_count', 'is_high_risk', 'had_major_procedure'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 54 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   sex                          100000 non-null  str
 3   region                       100000 non-null  str
 4   urban_rural                  100000 non-null  str
 5   income                       100000 non-null  float64
 6   education                    100000 non-null  str
 7   marital_status               100000 non-null  str
 8   employment_status            100000 non-null  str
 9   household_size               100000 non-null  int64
 10  dependents                   100000 non-null  int64
 11  bmi                          100000 non-null  float64
 12  smoker                       100000 non-null  str
 13  alcohol_freq                 69917 non-null   str
 14  visits_last_year             100000 non-null  int64
 15  hospitalizations_last_3yrs   100000 non-null  int64
 16  days_hospitalized_last_3yrs  100000 non-null  int64
 17  medication_count             100000 non-null  int64
 18  systolic_bp                  100000 non-null  float64
 19  diastolic_bp                 100000 non-null  float64
 20  ldl                          100000 non-null  float64
 21  hba1c                        100000 non-null  float64
 22  plan_type                    100000 non-null  str
 23  network_tier                 100000 non-null  str
 24  deductible                   100000 non-null  int64
 25  copay                        100000 non-null  int64
 26  policy_term_years            100000 non-null  int64
 27  policy_changes_last_2yrs     100000 non-null  int64
 28  provider_quality             100000 non-null  float64
 29  risk_score                   100000 non-null  float64
 30  annual_medical_cost          100000 non-null  float64
 31  annual_premium               100000 non-null  float64
 32  monthly_premium              100000 non-null  float64
 33  claims_count                 100000 non-null  int64
 34  avg_claim_amount             100000 non-null  float64
 35  total_claims_paid            100000 non-null  float64
 36  chronic_count                100000 non-null  int64
 37  hypertension                 100000 non-null  int64
 38  diabetes                     100000 non-null  int64
 39  asthma                       100000 non-null  int64
 40  copd                         100000 non-null  int64
 41  cardiovascular_disease       100000 non-null  int64
 42  cancer_history               100000 non-null  int64
 43  kidney_disease               100000 non-null  int64
 44  liver_disease                100000 non-null  int64
 45  arthritis                    100000 non-null  int64
 46  mental_health                100000 non-null  int64
 47  proc_imaging_count           100000 non-null  int64
 48  proc_surgery_count           100000 non-null  int64
 49  proc_physio_count            100000 non-null  int64
 50  proc_consult_count           100000 non-null  int64
 51  proc_lab_count               100000 non-null  int64
 52  is_high_risk                 100000 non-null  int64
 53  had_major_procedure          100000 non-null  int64
dtypes: float64(13), int64(31), str(10)
memory usage: 46.8 MB

In [9]:
df.describe()

,person_id,age,income,household_size,dependents,bmi,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,deductible,copay,policy_term_years,policy_changes_last_2yrs,provider_quality,risk_score,annual_medical_cost,annual_premium,monthly_premium,claims_count,avg_claim_amount,total_claims_paid,chronic_count,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
count,100000.000000,100000.000000,1.000000e+05,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000
mean,50000.500000,47.521500,4.987390e+04,2.430900,0.898380,26.990512,1.92765,0.093640,0.373350,1.236320,117.808970,73.604770,119.975065,5.605968,1226.725000,19.520400,5.517760,0.050690,3.598920,0.519849,3009.451907,582.320040,48.526668,1.62178,656.512084,1377.878827,0.724720,0.203450,0.085930,0.058870,0.035950,0.051170,0.021510,0.014620,0.014770,0.108310,0.130140,0.508530,0.158690,0.508390,0.50933,0.509140,0.367810,0.169700
std,28867.657797,15.988752,4.680021e+04,1.075126,0.950654,4.994883,1.73773,0.304848,1.373011,1.209358,15.369187,8.900924,30.262086,0.845996,1019.619375,10.286255,2.868827,0.224591,0.594052,0.250669,3127.462822,399.583722,33.298640,2.02982,1072.660048,2305.464687,0.805523,0.402566,0.280262,0.235382,0.186166,0.220345,0.145078,0.120027,0.120632,0.310773,0.336459,0.749755,0.463562,0.747218,0.75363,0.750455,0.482212,0.375371
min,1.000000,0.000000,1.100000e+03,1.000000,0.000000,12.000000,0.00000,0.000000,0.000000,0.000000,61.000000,40.000000,30.000000,3.540000,500.000000,10.000000,1.000000,0.000000,1.500000,0.000000,55.550000,211.670000,17.640000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
25%,25000.750000,37.000000,2.110000e+04,2.000000,0.000000,23.600000,1.00000,0.000000,0.000000,0.000000,107.000000,67.000000,99.400000,5.160000,500.000000,10.000000,3.000000,0.000000,3.200000,0.329700,1175.117500,352.070000,29.340000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
50%,50000.500000,48.000000,3.620000e+04,2.000000,1.000000,27.000000,2.00000,0.000000,0.000000,1.000000,117.000000,73.000000,120.000000,5.440000,1000.000000,20.000000,6.000000,0.000000,3.600000,0.505500,2082.575000,463.585000,38.630000,1.00000,318.015000,642.545000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000
75%,75000.250000,58.000000,6.220000e+04,3.000000,1.000000,30.400000,3.00000,0.000000,0.000000,2.000000,128.000000,79.000000,140.300000,5.760000,2000.000000,30.000000,8.000000,0.000000,4.010000,0.703300,3707.957500,666.697500,55.560000,2.00000,872.215000,1795.522500,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.00000,1.000000,1.000000,0.000000
max,100000.000000,100.000000,1.061800e+06,9.000000,7.000000,50.400000,25.00000,3.000000,21.000000,11.000000,183.000000,114.000000,248.300000,11.940000,5000.000000,50.000000,10.000000,2.000000,5.000000,1.000000,65724.900000,10962.550000,913.550000,23.00000,30010.530000,72517.950000,6.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7.000000,6.000000,7.000000,7.00000,7.000000,1.000000,1.000000

In [10]:
df.isnull().sum()

person_id              0
age                    0
sex                    0
region                 0
urban_rural            0
                      ..
proc_physio_count      0
proc_consult_count     0
proc_lab_count         0
is_high_risk           0
had_major_procedure    0
Length: 54, dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.nunique()

person_id              100000
age                       101
sex                         3
region                      5
urban_rural                 3
                        ...
proc_physio_count           8
proc_consult_count          8
proc_lab_count              8
is_high_risk                2
had_major_procedure         2
Length: 54, dtype: int64

In [13]:
df.sample(5)

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,dependents,bmi,smoker,alcohol_freq,visits_last_year,hospitalizations_last_3yrs,days_hospitalized_last_3yrs,medication_count,systolic_bp,diastolic_bp,ldl,hba1c,plan_type,network_tier,deductible,copay,policy_term_years,policy_changes_last_2yrs,provider_quality,risk_score,annual_medical_cost,annual_premium,monthly_premium,claims_count,avg_claim_amount,total_claims_paid,chronic_count,hypertension,diabetes,asthma,copd,cardiovascular_disease,cancer_history,kidney_disease,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
16472,13095,67,Female,North,Rural,10200.0,Bachelors,Married,Employed,2,0,31.1,Former,NaN,1,0,0,1,142.0,82.0,143.1,5.54,PPO,Bronze,1000,10,2,0,3.06,0.6264,1916.06,393.94,32.83,1,906.47,906.47,0,0,0,0,0,0,0,0,0,0,0,2,0,0,1,0,1,0
57696,23112,79,Female,South,Urban,15600.0,Some College,Single,Employed,2,1,34.7,Never,Occasional,1,0,0,1,131.0,70.0,110.3,5.00,EPO,Silver,2000,10,2,1,3.22,0.9560,3007.16,580.86,48.40,1,1319.10,1319.10,1,0,0,0,0,0,0,0,0,1,0,1,0,1,0,2,1,0
55032,94106,51,Male,North,Suburban,102400.0,HS,Married,Employed,2,0,29.4,Never,NaN,2,0,0,0,115.0,81.0,83.8,5.64,PPO,Gold,500,10,2,0,3.70,0.3626,1682.82,447.33,37.28,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0
82911,22004,49,Male,North,Urban,45500.0,HS,Widowed,Employed,1,0,26.2,Former,NaN,2,0,0,0,93.0,75.0,110.8,4.82,HMO,Gold,500,10,9,0,4.01,0.3407,3048.18,643.94,53.66,0,0.00,0.00,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
87451,41012,31,Male,North,Suburban,6800.0,Bachelors,Single,Unemployed,4,3,31.6,Never,Weekly,7,0,0,0,111.0,69.0,145.8,6.47,HMO,Gold,1000,20,6,0,2.76,0.6264,1670.57,450.56,37.55,4,438.15,1752.60,2,0,1,0,0,0,1,0,0,0,0,0,0,1,3,0,1,0

In [14]:
print(df.select_dtypes(include=['number']).columns)

Index(['person_id', 'age', 'income', 'household_size', 'dependents', 'bmi',
       'visits_last_year', 'hospitalizations_last_3yrs',
       'days_hospitalized_last_3yrs', 'medication_count', 'systolic_bp',
       'diastolic_bp', 'ldl', 'hba1c', 'deductible', 'copay',
       'policy_term_years', 'policy_changes_last_2yrs', 'provider_quality',
       'risk_score', 'annual_medical_cost', 'annual_premium',
       'monthly_premium', 'claims_count', 'avg_claim_amount',
       'total_claims_paid', 'chronic_count', 'hypertension', 'diabetes',
       'asthma', 'copd', 'cardiovascular_disease', 'cancer_history',
       'kidney_disease', 'liver_disease', 'arthritis', 'mental_health',
       'proc_imaging_count', 'proc_surgery_count', 'proc_physio_count',
       'proc_consult_count', 'proc_lab_count', 'is_high_risk',
       'had_major_procedure'],
      dtype='str')

In [15]:
print(df.select_dtypes(include=['object']).columns)

Index(['sex', 'region', 'urban_rural', 'education', 'marital_status',
       'employment_status', 'smoker', 'alcohol_freq', 'plan_type',
       'network_tier'],
      dtype='str')