In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../data/raw/medical_insurance.csv")

In [3]:
df.head()

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
0,75722,52,Female,North,Suburban,22700.0,Doctorate,Married,Retired,3,...,0,1,0,1,0,2,0,1,0,0
1,80185,79,Female,North,Urban,12800.0,No HS,Married,Employed,3,...,0,1,1,0,0,1,0,1,1,0
2,19865,68,Male,North,Rural,40700.0,HS,Married,Retired,5,...,0,0,1,1,0,2,1,0,1,0
3,76700,15,Male,North,Suburban,15600.0,Some College,Married,Self-employed,5,...,0,0,0,1,0,0,1,0,0,0
4,92992,53,Male,Central,Suburban,89600.0,Doctorate,Married,Self-employed,2,...,0,1,0,2,0,1,1,0,1,0

In [4]:
df.tail()

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
99995,6266,50,Male,West,Urban,127200.0,No HS,Married,Employed,2,...,0,0,0,0,0,1,0,0,0,0
99996,54887,42,Male,East,Suburban,21600.0,HS,Married,Employed,2,...,0,0,0,0,0,0,0,0,0,0
99997,76821,41,Male,West,Rural,81900.0,HS,Divorced,Unemployed,1,...,0,0,0,1,0,1,0,0,0,0
99998,861,51,Female,South,Urban,43400.0,Doctorate,Single,Unemployed,3,...,0,0,1,0,0,2,2,1,0,0
99999,15796,44,Female,South,Rural,43700.0,Some College,Married,Employed,2,...,0,0,0,0,0,1,1,1,0,0

In [5]:
df.sample(5)

,person_id,age,sex,region,urban_rural,income,education,marital_status,employment_status,household_size,...,liver_disease,arthritis,mental_health,proc_imaging_count,proc_surgery_count,proc_physio_count,proc_consult_count,proc_lab_count,is_high_risk,had_major_procedure
41102,23113,50,Female,West,Urban,31000.0,Bachelors,Single,Self-employed,3,...,0,0,0,1,0,0,0,0,0,0
69784,37221,60,Female,West,Suburban,22800.0,Some College,Single,Employed,3,...,0,0,0,0,0,0,0,4,1,0
20362,56460,61,Male,South,Rural,127300.0,Some College,Single,Self-employed,1,...,0,1,0,0,0,2,1,1,1,0
48472,21525,26,Male,South,Urban,6300.0,Some College,Divorced,Unemployed,1,...,0,0,0,1,0,1,0,0,0,0
71606,5338,35,Male,West,Rural,70500.0,Some College,Married,Self-employed,3,...,0,0,0,0,0,0,0,1,0,0

In [6]:
df.shape

(100000, 54)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 54 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   person_id                    100000 non-null  int64
 1   age                          100000 non-null  int64
 2   sex                          100000 non-null  str
 3   region                       100000 non-null  str
 4   urban_rural                  100000 non-null  str
 5   income                       100000 non-null  float64
 6   education                    100000 non-null  str
 7   marital_status               100000 non-null  str
 8   employment_status            100000 non-null  str
 9   household_size               100000 non-null  int64
 10  dependents                   100000 non-null  int64
 11  bmi                          100000 non-null  float64
 12  smoker                       100000 non-null  str
 13  alcohol_freq                 69917 non-null   str
 14  visits_last_year             100000 non-null  int64
 15  hospitalizations_last_3yrs   100000 non-null  int64
 16  days_hospitalized_last_3yrs  100000 non-null  int64
 17  medication_count             100000 non-null  int64
 18  systolic_bp                  100000 non-null  float64
 19  diastolic_bp                 100000 non-null  float64
 20  ldl                          100000 non-null  float64
 21  hba1c                        100000 non-null  float64
 22  plan_type                    100000 non-null  str
 23  network_tier                 100000 non-null  str
 24  deductible                   100000 non-null  int64
 25  copay                        100000 non-null  int64
 26  policy_term_years            100000 non-null  int64
 27  policy_changes_last_2yrs     100000 non-null  int64
 28  provider_quality             100000 non-null  float64
 29  risk_score                   100000 non-null  float64
 30  annual_medical_cost          100000 non-null  float64
 31  annual_premium               100000 non-null  float64
 32  monthly_premium              100000 non-null  float64
 33  claims_count                 100000 non-null  int64
 34  avg_claim_amount             100000 non-null  float64
 35  total_claims_paid            100000 non-null  float64
 36  chronic_count                100000 non-null  int64
 37  hypertension                 100000 non-null  int64
 38  diabetes                     100000 non-null  int64
 39  asthma                       100000 non-null  int64
 40  copd                         100000 non-null  int64
 41  cardiovascular_disease       100000 non-null  int64
 42  cancer_history               100000 non-null  int64
 43  kidney_disease               100000 non-null  int64
 44  liver_disease                100000 non-null  int64
 45  arthritis                    100000 non-null  int64
 46  mental_health                100000 non-null  int64
 47  proc_imaging_count           100000 non-null  int64
 48  proc_surgery_count           100000 non-null  int64
 49  proc_physio_count            100000 non-null  int64
 50  proc_consult_count           100000 non-null  int64
 51  proc_lab_count               100000 non-null  int64
 52  is_high_risk                 100000 non-null  int64
 53  had_major_procedure          100000 non-null  int64
dtypes: float64(13), int64(31), str(10)
memory usage: 46.8 MB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
person_id,100000.0,50000.500000,28867.657797,1.00,25000.7500,50000.5000,75000.2500,100000.00
age,100000.0,47.521500,15.988752,0.00,37.0000,48.0000,58.0000,100.00
income,100000.0,49873.905000,46800.214127,1100.00,21100.0000,36200.0000,62200.0000,1061800.00
household_size,100000.0,2.430900,1.075126,1.00,2.0000,2.0000,3.0000,9.00
dependents,100000.0,0.898380,0.950654,0.00,0.0000,1.0000,1.0000,7.00
bmi,100000.0,26.990512,4.994883,12.00,23.6000,27.0000,30.4000,50.40
visits_last_year,100000.0,1.927650,1.737730,0.00,1.0000,2.0000,3.0000,25.00
hospitalizations_last_3yrs,100000.0,0.093640,0.304848,0.00,0.0000,0.0000,0.0000,3.00
days_hospitalized_last_3yrs,100000.0,0.373350,1.373011,0.00,0.0000,0.0000,0.0000,21.00
medication_count,100000.0,1.236320,1.209358,0.00,0.0000,1.0000,2.0000,11.00
systolic_bp,100000.0,117.808970,15.369187,61.00,107.0000,117.0000,128.0000,183.00
diastolic_bp,100000.0,73.604770,8.900924,40.00,67.0000,73.0000,79.0000,114.00
ldl,100000.0,119.975065,30.262086,30.00,99.4000,120.0000,140.3000,248.30
hba1c,100000.0,5.605968,0.845996,3.54,5.1600,5.4400,5.7600,11.94
deductible,100000.0,1226.725000,1019.619375,500.00,500.0000,1000.0000,2000.0000,5000.00
copay,100000.0,19.520400,10.286255,10.00,10.0000,20.0000,30.0000,50.00
policy_term_years,100000.0,5.517760,2.868827,1.00,3.0000,6.0000,8.0000,10.00
policy_changes_last_2yrs,100000.0,0.050690,0.224591,0.00,0.0000,0.0000,0.0000,2.00
provider_quality,100000.0,3.598920,0.594052,1.50,3.2000,3.6000,4.0100,5.00
risk_score,100000.0,0.519849,0.250669,0.00,0.3297,0.5055,0.7033,1.00
annual_medical_cost,100000.0,3009.451907,3127.462822,55.55,1175.1175,2082.5750,3707.9575,65724.90
annual_premium,100000.0,582.320040,399.583722,211.67,352.0700,463.5850,666.6975,10962.55
monthly_premium,100000.0,48.526668,33.298640,17.64,29.3400,38.6300,55.5600,913.55
claims_count,100000.0,1.621780,2.029820,0.00,0.0000,1.0000,2.0000,23.00
avg_claim_amount,100000.0,656.512084,1072.660048,0.00,0.0000,318.0150,872.2150,30010.53
total_claims_paid,100000.0,1377.878827,2305.464687,0.00,0.0000,642.5450,1795.5225,72517.95
chronic_count,100000.0,0.724720,0.805523,0.00,0.0000,1.0000,1.0000,6.00
hypertension,100000.0,0.203450,0.402566,0.00,0.0000,0.0000,0.0000,1.00
diabetes,100000.0,0.085930,0.280262,0.00,0.0000,0.0000,0.0000,1.00
asthma,100000.0,0.058870,0.235382,0.00,0.0000,0.0000,0.0000,1.00
copd,100000.0,0.035950,0.186166,0.00,0.0000,0.0000,0.0000,1.00
cardiovascular_disease,100000.0,0.051170,0.220345,0.00,0.0000,0.0000,0.0000,1.00
cancer_history,100000.0,0.021510,0.145078,0.00,0.0000,0.0000,0.0000,1.00
kidney_disease,100000.0,0.014620,0.120027,0.00,0.0000,0.0000,0.0000,1.00
liver_disease,100000.0,0.014770,0.120632,0.00,0.0000,0.0000,0.0000,1.00
arthritis,100000.0,0.108310,0.310773,0.00,0.0000,0.0000,0.0000,1.00
mental_health,100000.0,0.130140,0.336459,0.00,0.0000,0.0000,0.0000,1.00
proc_imaging_count,100000.0,0.508530,0.749755,0.00,0.0000,0.0000,1.0000,7.00
proc_surgery_count,100000.0,0.158690,0.463562,0.00,0.0000,0.0000,0.0000,6.00
proc_physio_count,100000.0,0.508390,0.747218,0.00,0.0000,0.0000,1.0000,7.00
proc_consult_count,100000.0,0.509330,0.753630,0.00,0.0000,0.0000,1.0000,7.00
proc_lab_count,100000.0,0.509140,0.750455,0.00,0.0000,0.0000,1.0000,7.00
is_high_risk,100000.0,0.367810,0.482212,0.00,0.0000,0.0000,1.0000,1.00
had_major_procedure,100000.0,0.169700,0.375371,0.00,0.0000,0.0000,0.0000,1.00

In [10]:
missing = df.isnull().sum()

missing[missing > 0]

alcohol_freq    30083
dtype: int64

In [11]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [12]:
df.nunique().sort_values(ascending=False)

person_id                      100000
annual_medical_cost             91299
total_claims_paid               56650
annual_premium                  55538
avg_claim_amount                53071
monthly_premium                 12339
income                           2987
ldl                              1881
hba1c                             732
provider_quality                  350
bmi                               340
systolic_bp                       119
age                               101
risk_score                         92
diastolic_bp                       72
claims_count                       22
visits_last_year                   22
days_hospitalized_last_3yrs        16
medication_count                   12
policy_term_years                  10
household_size                      9
dependents                          8
proc_imaging_count                  8
proc_physio_count                   8
proc_lab_count                      8
proc_consult_count                  8
proc_surgery_count                  7
chronic_count                       7
education                           6
region                              5
copay                               4
deductible                          4
network_tier                        4
plan_type                           4
employment_status                   4
marital_status                      4
hospitalizations_last_3yrs          4
urban_rural                         3
smoker                              3
alcohol_freq                        3
sex                                 3
policy_changes_last_2yrs            3
hypertension                        2
diabetes                            2
copd                                2
asthma                              2
arthritis                           2
liver_disease                       2
kidney_disease                      2
cancer_history                      2
cardiovascular_disease              2
mental_health                       2
is_high_risk                        2
had_major_procedure                 2
dtype: int64